### PR TITLE
Code cleanup

### PR DESCRIPTION
**Pull request by sindresorhus**
Fixed all the mixed tabs/space and code style inconsistencies. Sorry, just had too, otherwise I'll go insane.

Also added a grunt task for creating a release. You only run this before tagging a release. This way you only generate files in the dist folder on a release, and don't dirty up every commit.

Just run `grunt` to lint and test when you develop, and run `grunt release` to create release versions in the dist folder.

### CODE REVIEW

**Comment by addyosmani** [comment]
By the looks of it this should hopefully put the nail in the coffin on the tab/space inconsistencies. Thanks, Sindre! Appreciate the extra grunt tasks you've added too.

//cc @peol

**Comment by addyosmani** [comment]
@sindresorhus I've just added you as a collab to the repo. If there are any grunt related updates you feel are necessary to the project, please feel free to go ahead and merge to master. You know what you're doing :) 

If you'd prefer to have a review, more than don't mind reviewing before we merge. Thanks!

**Comment by sindresorhus** [comment]
:)

**Comment by peol** [comment]
Great. Before release, I'll do a complete reformatting on the file (and QUnit tests) so we can maintain it easier. Thanks @sindresorhus!

**Comment by sindresorhus** [comment]
@addyosmani @peol What are your thoughts about following the [idionmatic.js style guide](https://github.com/rwldrn/idiomatic.js/)?

**Comment by addyosmani** [comment]
@sindresorhus I believe I have it listed under a recommended reading section on my site :) Love Rick's idiomatic guide. In terms of code style he generally advocates the jQuery style guide but I don't mind us adopting any additional syntax/style recommendations be has that could be useful (as long as they don't slow us down too much) ; )

**Comment by sindresorhus** [comment]
@addyosmani It's almost identical to the jQuery style, only more thoroughly explained. It won't slow you down if you use it consistently everywhere, it will actually make you faster, since you now longer need to think about how to format your code, it just muscle memory.

**Comment by peol** [comment]
Yes, that looks exactly what I want and pushing for at work. Feel free to fix it whenever, or I'll tackle it soonish. I think we need to sync this with any work that is done elsewhere to ease merging. I got one pull request pending, but after that I can wait 'til this is done. :)

**Comment by addyosmani** [comment]
Let's go for it. Is it worth adding a reference to the guide in our readme?

**Comment by peol** [comment]
That would be great!

2012/3/4 Addy Osmani <
reply@reply.github.com

**Comment by sindresorhus** [comment]
Done ;)

**Comment by addyosmani** [comment]
Haha. Thanks. I think we were adding it at the same time. I've just pushed some updates to extend the language a bit in style guide and testing sections. Also added a team section just so people know we're all working on it.

**Comment by sindresorhus** [comment]
Np, your was better ;)

**Pull request merged**
