### PR TITLE
clear() method

### PR DESCRIPTION
**Pull request by sindresorhus**
Thought this might be useful. 

Usecase:
Devs wanting to clear out everything added to localStorage as cache with basket.js, but not everything else.

### CODE REVIEW

**Comment by peol** [comment]
Absolutely, I thought about this earlier today when I submitted the other issue. I thought `.reset()` though, but that's just semantics. :)

+1

**Comment by peol** [comment]
However, I think we should use `new RegExp` and use the `storagePrefix` value so we don't have to maintain it on several places if we choose another prefix.

**Comment by sindresorhus** [comment]
> However, I think we should use new RegExp and use the storagePrefix value so we don't have to maintain it on several places if we choose another prefix.

I don't see why. It's not like we're going to change it often. We're probably not going to change it at all.

Using a regex literal is [twice as fast](http://jsperf.com/regexp-literal-vs-new-construction/2) as using the constructor, so I feel pretty strongly about not using the constructor.

**Comment by peol** [comment]
If we love it to the top it'll only run once, doubt we'd see a noticeably
performance hit. It's just a maintainability question, to be on the safe
side.
On Mar 18, 2012 4:44 PM, "Sindre Sorhus" <
reply@reply.github.com>
wrote:

**Comment by peol** [comment]
Move*

Also, there might be a use case to allow the prefix to be configurable
later on.

**Comment by sindresorhus** [comment]
Yes, I realize it's not any noticeable performance improvement, but it is best practice to use the literal whenever possible. Either way, the prefix is static, and not something that is going to change anytime soon. We shouldn't love it to the top anyway, since that would create a unnecessary "global".

> Also, there might be a use case to allow the prefix to be configurable
> later on.

Do we really want to do premature feature facilitation? Can't we just handle it when or if the time comes?

**Comment by addyosmani** [comment]
Nice work, Sindre. I'm happy with us proceeding with this in its current form. We're going to review the naming of all API methods prior to the next release so Im okay with us referring on naming changes till then.

**Pull request merged**
