### PR TITLE
Made it pretty

### PR DESCRIPTION
**Pull request by passy**
Sorry to be blunt, but no one could read that mess. Given it's a new quarter I thought I'd help you out and make it readable. And don't worry, the tests are passing.

### CODE REVIEW

**Comment by wibblymat** [comment]
LGTM. Now all of the code is in a consistent style with my other projects, awesome!

@addyosmani @sindresorhus

**Comment by sindresorhus** [comment]
lgtm. let's merge when @addyosmani has reviewed.

**Comment by addyosmani** [comment]
thumbs-up-matt-leblanc

**Comment by passy** [comment]
Didn't notice I also got #100 with this. Hell yeah!

**Pull request closed without merging**
