### PR TITLE
Scripts begin loading immediately when you call thenRequire (#67)

### PR DESCRIPTION
**Pull request by wibblymat**
Doing this a pull request to get a review.

### CODE REVIEW

**Comment by addyosmani** [comment]
The implementation review lgtm so far, but it would be great to get a few more tests in :)

**Comment by wibblymat** [comment]
Tried to use Sinon to mock up the XHRs happening in the "wrong" order but I'm not sure if you can do that (I've asked about it at https://groups.google.com/forum/?fromgroups=#!topic/sinonjs/mcIGkiNZdcY).

Test case coverage still better now though.

**Comment by addyosmani** [comment]
Thanks for improving the test coverage of the implementation. I think that since we're not tight for time on the next release it would be useful to wait on a reply to the group thread. Alternatively, maybe there's a way a Sinon helper could be written that does provide the async. behavior you're after?

**Comment by addyosmani** [comment]
Let's chase this up again before we want to do another release. I think there's room for us to address both plugins and this for it.

**Comment by wibblymat** [comment]
I had a response to the Google Groups post I made but I had forgotten to turn on email updates so hadn't seen it.

I've updated the ordering test based on that. I don't have anything else I was intending to update on this so I'll squash the commits and merge when I get a moment.

**Pull request merged**
