### PR TITLE
Handle resources other than JavaScript

### LINKED ISSUE #77: Discussion of plugins for new resource types
I created [a gist](https://gist.github.com/wibblymat/4754410) with some thoughts on the subject based on @addyosmani's question at https://github.com/addyosmani/basket.js/pull/76#issuecomment-13333077.

Discuss!

@peol @sindresorhus

### PR DESCRIPTION
**Pull request by wibblymat**
Work in progress. Don't merge yet.

This doesn't quite close #77 because I didn't implement the `live` parameter that I describe in the doc.
It also doesn't fix #76 or #60 because there is no example CSS handler or any documentation.

I think this is the meat of the implementation though, so please sanity check the work so far.

### CODE REVIEW

**Comment by peol** [comment]
Looks good to me, great work so far!

**Comment by addyosmani** [comment]
Whoa! We were not expecting to see this so soon. Great work, @wibblymat :cake:

**Comment by addyosmani** [comment]
Re-reading through the proposal, (forgive me ignorance) but I couldn't fully understand the use case for caching the result, but always fetching `live`. Is the idea that some other process may consume the cached data but the loader in that scenario just cares about always fetching latest regardless?

**Comment by wibblymat** [comment]
It's for use by web apps that _may_ be offline. In the example of a Twitter client, let's say that in the morning I go fetch your tweets while online. Later on I'm on the tube and go back to get your tweets. I can't get a live version, but I can get it from the cache and show a message letting the user know that the data is not fresh.

This requires that the data is cached, so it goes through basket and we want to cache for a longish time (a week maybe). But when we have connection we want to get the latest, and update the cache with that.

Does that make sense?

The logic should probably be:
- `live` is false
  - behave as now, returning from the cache if possible, over the network otherwise.
- `live` is true and can't fetch (timeout or navigator.onLine === false, not just a 404)
  - return from cache if available, perhaps flag that the result is not live even though it was requested
- `live` is true and network is available
  - fetch over the network and update the cache

**Comment by addyosmani** [comment]
Aha. Now that makes sense. Thanks for the explanation :)

**Comment by addyosmani** [comment]
:+1:

**Comment by addyosmani** [comment]
Spoke to @wibblymat about this yesterday. It looks like we should just need some docs changes and should be in a good position to land once those are written up. Great work once again!

**Comment by addyosmani** [comment]
Time to merge this baby! Let's handle docs as part of #85 :dancer:

**Pull request merged**
