### PR TITLE
TTL - some features

### PR DESCRIPTION
**Pull request by felipemorais**
`clear()` was modified to support remove only expired keys. It could be `clear( true )`.

new function `addLocalStorage` allow that new keys can be cached. If the available quota is insufficient, an old key will be removed recursively until the new key can be added.

### CODE REVIEW

**Comment by addyosmani** [comment]
Is it possible to get this to pass the build? Nice work, otherwise :)

**Comment by felipemorais** [comment]
Sorry. I didn't lint before push.

**Comment by sindresorhus** [comment]
Landed. Thanks :)

Can you update the docs about the clear(true) and the new behavior?

**Comment by felipemorais** [comment]
Yes, I was waiting for any changes!

**Pull request closed without merging**
