### PR TITLE
RSVP flavour promises

### PR DESCRIPTION
**Pull request by wibblymat**
Its probably easier to discuss a Pull Request than to keep linking to commits in my own branch in #45.

### CODE REVIEW

**Comment by wibblymat** [comment]
Ah, build fails because no rsvp.js in the repo. Sadly, only the node module version is in the rsvp node package (which makes sense) so making it a dependency doesn't give us a useable version. I'm satisfied the tests pass when there is a copy of rsvp.js linked in the test/index.html

To be honest I have no experience with JS projects that have external dependencies so I don't know what the convention/pattern is for this.

**Comment by sindresorhus** [comment]
We'll get it into Bower using a fork for now, placed here probably: https://github.com/components

**Comment by addyosmani** [comment]
I think getting it on Bower makes sense. @wibblymat would you like to try registering it as a Bower package?

**Comment by wibblymat** [comment]
Sure, though I'm going to have to ask a lot of noob questions here first :)
- Should I try to get a component.json file into the upstream repo first?
- The github.com/components org that @sindresorhus mentioned contains just the components.json and the library for each project. Should I create a repo like that or would I register a full fork of the project?
- If a full fork, should it include the .all() method we want? I'd guess no so as not to confuse others.

Anyhow, I tagged a clean fork of upstream with a components.json added at https://github.com/wibblymat/rsvp.js/tree/1.0.0

**Comment by sindresorhus** [comment]
> Should I try to get a component.json file into the upstream repo first?

You could try, but I'm pretty sure they won't. They also still have an open PR for a component.json file for another package manager: _component(1)_

> The github.com/components org that sindresorhus mentioned contains just the components.json and the library for each project. Should I create a repo like that or would I register a full fork of the project?

Just create a repo like that. Created the repo and added you: https://github.com/components/rsvp.js

> If a full fork, should it include the .all() method we want? I'd guess no so as not to confuse others.

No

**Comment by wibblymat** [comment]
Ok, I think we're all good now.

**Comment by sindresorhus** [comment]
@wibblymat Landed. Thank you so much for this! :hamburger:  Really great to have promises. Would you be interested in doing a PR to update the docs accordingly?

**Comment by addyosmani** [comment]
I just wanted to say how stoked I am for us to have this in place. An update to the docs would be fantastic to have.

**Pull request closed without merging**
