### PR TITLE
Added support for overridden key name, modified the add() signature

### PR DESCRIPTION
**Pull request by peol**
This commit adds support for custom key names:

```
basket.add("jquery-1.7.1.js", { key: "jquery" });
```

```
basket.require("jquery");
```

```
basket.remove("jquery");
```

The signature also changed to:

```
basket.add("jquery-1.7.1", { key: "foo", overwrite: false }, function() {
});
```

### CODE REVIEW

**Comment by addyosmani** [comment]
Thanks a ton for this @peol!. 

@mahemoff does this address the main points for what you were suggesting in #2? (we decided to not go for the magic option just yet) :)

**Comment by peol** [comment]
If so, I think issue #2 can be closed with this.

**Comment by mahemoff** [comment]
It does, great job @peol. I do suggest this gets added to require() as well (which in practice will get used much more than add() imo).

**Comment by peol** [comment]
@mahemoff Ah, true. I didn't think about that. I'll look into that after lunch (GMT).

**Pull request merged**
