### PR TITLE
Add compress option and lz-string dependency

### PR DESCRIPTION
**Pull request by lagden**
Possibility of store large scripts...

### CODE REVIEW

**Comment by addyosmani** [comment]
This fails the build. Could you take a look at the cause?

**Comment by lagden** [comment]
Oh my!!!

The test works when executed locally.
In my test (`compressed script`), I had to change the big file to small file because the `Travis` was giving timeout.

Now I can have lunch in peace... rs...

**Comment by addyosmani** [comment]
Closing due to the age of this PR. We appreciate you originally working on this regardless, @lagden :)

**Comment by lagden** [comment]
Ok!! Tks!

**Pull request closed without merging**
