### PR TITLE
experiment loading css via Basket.js

### PR DESCRIPTION
**Pull request by amrnt**
I dont know if this makes sense :relaxed:

### CODE REVIEW

**Comment by addyosmani** [comment]
Thanks for the PR, @amrnt.  Some background info: when I created the first version of basket, I purposefully left out support for CSS loading of assets as this was something deemed inappropriate for localStorage caching by a few members of the community. This was in part because we want to avoid any FOUT but also, once you move beyond scripts you begin to get into AppCache territory (which arguably is better suited to CSS).

I won't close this immediately, but it would be useful to hear what @peol and @sindresorhus think.

**Comment by peol** [comment]
I agree that this is something we might consider in the future, but there's a lot of quirks that needs to be worked out. Loading CSS, even if FOUT wasn't an issue, is still problematic and I think basket.js should focus on stabilizing the script-loading part for now.

Thanks for the contribution though, @amrnt :)

**Comment by sindresorhus** [comment]
I agree, we should wait.

**Comment by addyosmani** [comment]
As we appear to be at an agreement about shelfing this, I'm going to close for now. We can revisit the PR if we decide to change our mind about this in the future (or at most, document in the wiki for anyone wondering about the same).

**Comment by amrnt** [comment]
@addyosmani I was going to say the same.

**Pull request closed without merging**
