### PR TITLE
Grunt build script

### LINKED ISSUE #11: Use grunt, be happy.
Recommend rebuilding the repo with `grunt`... it will make life easier. I promise.

### PR DESCRIPTION
**Pull request by sindresorhus**
Added [grunt](https://github.com/cowboy/grunt) build script. Fixes #11.

You can now just run `grunt` in Terminal in the basket.js folder, and it will jshint all the files, run the QUnit tests headless in PhantomJS [1] and then minify the code and add comment header based on the package.json file.

[1]: Which means you don't have to open the browser each time to test the changes.

### CODE REVIEW

**Comment by addyosmani** [comment]
Whoa. This was a nice surprise. Thank you so much for your time on this, Sindre.

Would you like to add yourself to the contribs list just for funsies? This is a pretty nice addition. Happy to merge after.

**Comment by sindresorhus** [comment]
@addyosmani Sure, added ;)

**Comment by rwaldron** [comment]
I just decided to pull from the upstream for the first time since this morning and was delighted to see this :D

**Comment by sindresorhus** [comment]
@rwldrn I've fallen in love with grunt, so this was a nobrainer ;)

**Comment by rwaldron** [comment]
Same here :)

**Pull request merged**
